with-expecter: true
resolve-type-alias: false
dir: "{{.InterfaceDir}}/mocks"
outpkg: "mocks"
filename: "{{.InterfaceName|lower}}_mock.go"
mockname: "{{.InterfaceName}}"
issue-845-fix: true
packages:
    github.com/jfilipedias/tidy-url/url:
      config:
        all: true