version: '3.1'
name: tidy-url
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./**/*.go
          target: /app
          ignore: 
            - ./**/*_mock.go
            - ./**/*_test.go
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      mongodb:
        condition: service_started
  mongodb:
    image: mongodb/mongodb-community-server:7.0.16-ubi8
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017